"""The factual claims the revised Related Work makes about each paper, with the pattern that
evidences each claim in the paper's extracted text. verify_facts.py checks them.
(key, regex, claim). Patterns run case-insensitively on whitespace-normalised text."""

FACTS = [
    # --- benchmarks that score final answers, options or tests -----------------------------
    ("cobbe2021gsm8k", r"correct final answer using flawed reasoning", "Notes that solutions can reach the correct final answer through flawed reasoning."),
    ("hendrycks2021math", r"step-by-step solution", "Every MATH problem has a full step-by-step solution."),
    ("hendrycks2021mmlu", r"electrical engineering", "MMLU has an electrical-engineering task."),
    ("du2025supergpqa", r"7,?892", "SuperGPQA has 7,892 engineering questions."),
    ("du2025supergpqa", r"42\.33", "42.33% of SuperGPQA questions require calculation."),
    ("jimenez2024swebench", r"GitHub issues", "SWE-bench is built from real GitHub issues."),
    # --- physics and science ----------------------------------------------------------------
    ("xu2025ugphysics", r"MARJ|Model-Assistant Rule-based", "UGPhysics scores final answers with rules plus a model-assisted judge (MARJ)."),
    ("zhang2025physreason", r"first error", "PhysReason's step-level scoring locates the first error step."),
    ("zhang2025physreason", r"98\.0", "PhysReason's step scorer was checked against annotated solutions (about 98% first-error accuracy)."),
    ("qiu2025phybench", r"Expression Edit Distance", "PHYBench scores final expressions with an expression edit distance."),
    ("zhang2025abenchphysics", r"Phy_?B", "ABench-Physics has a dynamic subset (Phy_B) of perturbed variants."),
    ("zhang2025abenchphysics", r"1\s?%", "ABench-Physics grades numerical answers with a 1% tolerance."),
    ("wang2023scibench", r"5\s?%", "SciBench grades numerical answers with a 5% relative tolerance."),
    ("zhao2026prismphysics", r"0\.346", "PRISM-Physics' step scoring agrees with experts better than an LLM judge (Kendall tau-b 0.346)."),
    ("zhao2026prismphysics", r"formula", "PRISM-Physics scores steps by matching formulas against a reference solution."),
    ("yu2026hipho", r"marking scheme", "HiPhO grades with the official marking schemes."),
    ("yu2026hipho", r"13 (latest )?(Olympiad|olympiad|physics)", "HiPhO is built from 13 olympiad exams."),
    # --- generated instances, contamination, saturation -------------------------------------
    ("ott2022saturation", r"saturat", "Documents benchmark saturation."),
    ("deng2024contamination", r"contamination", "Documents data contamination of benchmarks."),
    ("akhtar2026benchmarksaturation", r"\b60\b", "Studies 60 LLM benchmarks."),
    
    ("akhtar2026benchmarksaturation", r"private test sets or closed-ended formats, have limited impact", "Safeguards such as private test sets have limited impact on saturation."),
    ("akhtar2026benchmarksaturation", r"nearly half", "Nearly half of the benchmarks exhibit saturation."),
    ("zhang2024gsm1k", r"up to (8|13)\s?%", "GSM1k finds accuracy drops of up to 8% (13% in an earlier version)."),
    ("chen2025staticdynamicsurvey", r"dynamic benchmark", "Surveys the move from static to dynamic benchmarks."),
    ("srivastava2024functionalbench", r"reasoning gap", "Introduces functional variants and the reasoning gap."),
    ("mirzadeh2024gsmsymbolic", r"symbolic template", "GSM-Symbolic generates instances from symbolic templates."),
    ("gulati2024putnamaxiom", r"variation", "Putnam-AXIOM has programmatic variations of its problems."),
    ("huang2025mathperturb", r"hard perturbation|MATH-P-Hard", "MATH-Perturb's hard perturbations change the solution path."),
    ("cheng2026vera", r"84\.46|70\.25", "VeRA: AIME-2024 accuracy falls on fresh instances (84.46% to 70.25%)."),
    ("dlugosz2026gsmsymbolicreeval", r"mixed", "Re-analyses GSM-Symbolic with mixed models."),
    ("dlugosz2026gsmsymbolicreeval", r"Holm", "Applies a multiple-comparison (Holm) correction."),
    ("mondorf2026lpds", r"overestimate robustness", "Randomly sampled instances can overestimate robustness."),
    ("lunardi2025paraphraserobustness", r"ranking", "Paraphrasing changes absolute scores more than rankings."),
    ("xiao2026contaminationrankings", r"paraphras", "Measures contamination as an original-versus-paraphrase contrast."),
    ("fan2024hardmath", r"step-by-step", "HARDMath generates step-by-step solutions."),
    ("fan2024hardmath", r"numerical", "HARDMath validates its solutions numerically."),
    ("xie2025finchain", r"ChainEval", "FinChain scores steps with ChainEval against a gold chain."),
    ("xie2025finchain", r"executable", "FinChain's gold chains are executable."),
    ("imani2025sympybench", r"15,?045", "SymPyBench has 15,045 parameterised problems."),
    ("imani2025sympybench", r"Python", "Each SymPyBench problem is executable Python."),
    ("li2025atmosscibench", r"\b67\b", "AtmosSci-Bench has 67 expert-written templates."),
    ("li2025atmosscibench", r"Python", "AtmosSci-Bench templates have Python solvers."),
    ("azmi2026scirho", r"\b606\b", "Sci-rho has 606 templates."),
    ("azmi2026scirho", r"F1", "Sci-rho scores steps with an F1 measure."),
    # --- engineering ------------------------------------------------------------------------
    ("syed2024transportbench", r"Flawed Reasoning with Correct Conclusion", "TransportBench documents correct conclusions reached through flawed reasoning."),
    ("syed2024transportbench", r"used by human experts to evaluate", "TransportBench responses are evaluated by human experts, reasoning included."),
    ("kevian2024controlbench", r"human (domain )?experts|panel of", "ControlBench responses were evaluated by human experts."),
    ("cheng2024elecbench", r"logicality", "ElecBench scores reasoning with a logicality metric."),
    ("li2025eeebench", r"2,?860", "EEE-Bench has 2,860 problems."),
    ("skelic2025circuit", r"\b102\b", "CIRCUIT is built from 102 templates."),
    ("skelic2025circuit", r"numerical setup", "Each CIRCUIT template has several numerical setups."),
    ("chen2025apbench", r"Di Wu", "APBench's first author is Di Wu."),
    ("duzkar2026thermoqa", r"CoolProp", "ThermoQA's reference values are computed with CoolProp."),
    ("duzkar2026thermoqa", r"\b293\b", "ThermoQA has 293 problems."),
    ("zheng2026tpscalcbench", r"\b420\b", "TPS-CalcBench has 420 core items."),
    ("zheng2026tpscalcbench", r"0\.68", "TPS-CalcBench's judge was calibrated against an expert (weighted kappa from 0.68)."),
    ("mostajabdaveh2025orqa", r"Operations Research", "ORQA is an operations-research reasoning benchmark."),
    ("zhou2025engibench", r"GPT-4\.1 and Gemini 2\.5 Flash", "EngiBench answers are judged by two LLM evaluators (GPT-4.1, Gemini 2.5 Flash)."),
    ("zhou2025engibench", r"rubric", "EngiBench's open-ended level is scored with rubrics."),
    ("naser2026eri", r"57,?750", "ERI has 57,750 records."),
    ("naser2026eri", r"GPT-5 Mini|GPT-5-mini", "ERI's questions and references were generated by GPT-5 Mini."),
    ("wasiq2026engvqa", r"\b696\b", "EngVQA has 696 problems."),
    ("wasiq2026engvqa", r"eight|8 (solution )?stages", "EngVQA scores eight solution stages."),
    ("trashchenkov2026psab", r"seed", "The power-systems benchmark's held-out cases come from seeded generators."),
    ("trashchenkov2026psab", r"private", "Those seeds are private."),
    ("guo2025engdesign", r"simulation", "EngDesign checks designs by simulation."),
    ("mudur2025feabench", r"executab", "FEABench measures executability and other intermediate properties."),
    ("heesch2025realworld", r"easily verifiable", "Heesch et al. criticise exam-style items whose correctness is easily verifiable."),
    # --- process supervision and evaluator validity -----------------------------------------
    ("uesato2022processoutcome", r"similar final-answer error", "Outcome supervision gives similar final-answer error..."),
    ("uesato2022processoutcome", r"for correct reasoning steps we find it necessary to use process-?based supervision", "...but correct reasoning steps need process-based supervision or reward models that emulate it."),
    ("lightman2023verify", r"PRM800K", "Lightman et al. release PRM800K, human step labels."),
    ("wang2023mathshepherd", r"without (any )?human annotation|automatically", "Math-Shepherd's step labels are constructed automatically."),
    ("zhang2025prmlessons", r"Monte Carlo", "Qwen PRM lessons: Monte Carlo step labels."),
    ("zhang2025prmlessons", r"Best-of-N|BoN", "Qwen PRM lessons: Best-of-N evaluation bias."),
    ("zheng2024processbench", r"3,?400", "ProcessBench has 3,400 test cases."),
    ("zheng2024processbench", r"Process errors \(correct final answers\)", "ProcessBench reports the share of correct-final-answer samples with process errors..."),
    ("zheng2024processbench", r"3\.5%.{0,60}51\.8%", "...3.5% on GSM8K rising to 51.8% on Omni-MATH."),
    ("song2025prmbench", r"6,?216", "PRMBench has 6,216 problems."),
    ("zeng2025versaprm", r"multi-domain", "VersaPRM is a multi-domain PRM."),
    ("sun2026lsrben", r"rather than being confined to the mathematical domain", "LSR-Ben evaluates PRMs on scientific and logical reasoning rather than mathematics."),
    
    ("wang2026prime", r"engineering", "PRIME covers engineering."),
    ("wang2026prime", r"spurious", "PRIME targets spurious correctness."),
    ("guo2026chemcotbenchv2", r"0\.74", "ChemCoTBench-V2's verifier agrees with chemists at kappa 0.74."),
    ("guo2026chemcotbenchv2", r"RDKit", "ChemCoTBench-V2 checks steps with RDKit rules."),
    ("xia2024reasoneval", r"redundan", "ReasonEval scores step validity and redundancy."),
    ("golovneva2022roscoe", r"step-by-step", "ROSCOE scores step-by-step reasoning."),
    ("zheng2023mtbench", r"self-enhancement bias", "MT-Bench names self-enhancement bias."),
    ("panickssery2024selfrecognition", r"self-recognition", "Self-recognition..."),
    ("panickssery2024selfrecognition", r"self-preference", "...linked to self-preference."),
    ("li2026preferenceleakage", r"preference leakage", "Judges favour related models (preference leakage)."),
    ("spiliopoulou2025playfavorites", r"famil", "Judges favour their own family's outputs."),
    ("pombal2026rubricselfpreference", r"objective", "Self-preference persists on objective rubric items."),
    ("pombal2026rubricselfpreference", r"ensembl", "Ensembling reduces but does not remove it."),
    ("kim2025correlatederrors", r"60\s?%", "Models agree on 60% of their errors."),
    ("goel2025greatmodels", r"CAPA", "Goel et al. measure similarity of mistakes (CAPA)."),
    ("tan2025judgebench", r"random guessing|slightly better than random|barely", "JudgeBench: strong judges perform barely better than random."),
    ("krumdick2026nofreelabels", r"only on questions the judges were able to correctly answer themselves", "Without a reference, judges agree with experts mainly on questions they can answer themselves."),
    ("krumdick2026nofreelabels", r"expert-written references largely mitigates", "Expert-written references largely mitigate this."),
    ("huang2026verifierrobustness", r"false negative", "Rule-based verifiers give false negatives..."),
    ("huang2026verifierrobustness", r"misclassify certain patterns in responses as correct", "...model-based verifiers can be hacked into accepting wrong responses."),
    ("verga2024poll", r"Panel of LL[Mm]", "PoLL: a panel of LLM evaluators."),
    ("verga2024poll", r"intra-model|own (outputs|generations)|self-?preference", "PoLL reports judges favouring their own model's outputs."),

    # --- added for the final text and the comparison table ---------------------------------
    ("du2025supergpqa", r"55\.40", "55.40% of SuperGPQA engineering questions require calculation."),
    ("heesch2025realworld", r"examination materials", "Heesch et al. on items adapted from examination materials."),
    ("kim2025correlatederrors", r"provider", "Error correlation holds across providers."),
    ("huang2026verifierrobustness", r"format", "Rule-based verifiers miss answers in unexpected formats."),
    ("song2025prmbench", r"mathemat", "PRMBench is a mathematical benchmark."),
    ("zhang2025prmlessons", r"nois", "Monte Carlo step labels are noisy."),
    ("azmi2026scirho", r"step", "Sci-rho instances come with reasoning steps."),
    ("imani2025sympybench", r"step-by-step|step by step", "SymPyBench problems have step-by-step reasoning."),
    ("imani2025sympybench", r"consisten", "SymPyBench scores consistency across variants."),
    ("skelic2025circuit", r"Approximately 5% of the automated evaluations resulted in false positives", "CIRCUIT's human review found about 5% false positives."),
    ("zhou2025engibench", r"Level 3 scores are subsequently reviewed and calibrated by human annotators", "EngiBench's Level 3 scores are reviewed by human annotators."),
    ("zhou2025engibench", r"manual verification is performed", "Disagreements between its two LLM evaluators are resolved manually."),
    ("duzkar2026thermoqa", r"Weighted step-level scoring", "ThermoQA scores weighted solution steps..."),
    ("duzkar2026thermoqa", r"2% relative tolerance", "...with a 2% relative tolerance."),
    ("zheng2026tpscalcbench", r"weighted Cohen", "TPS-CalcBench reports weighted Cohen's kappa for its judge per rubric dimension."),
    ("zheng2026tpscalcbench", r"0\.82", "...weighted kappa up to 0.82."),
    ("wasiq2026engvqa", r"synthetic human", "EngVQA's human scores are synthetic adjustments of the judge's scores."),
    ("naser2026eri", r"five-point scale", "ERI responses are scored on a five-point scale."),
    ("guo2026chemcotbenchv2", r"87\.4% of step judgments", "ChemCoTBench-V2's verifier agrees with adjudicated expert labels on 87.4% of steps..."),
    ("guo2026chemcotbenchv2", r"human-human agreement was 90\.1%", "...against 90.1% between the experts themselves."),
    ("xie2025finchain", r"0\.655", "ChainEval correlates with expert ratings at Spearman 0.655."),
    ("zhang2025physreason", r"1,?000", "PhysReason's scorer was checked on 1,000 annotated solutions."),
    ("trashchenkov2026psab", r"41", "The power-systems benchmark has 41 task families."),
    ("mondorf2026lpds", r"EngTrace|EngChain", "LPDS evaluates on EngTrace templates (relevant to anonymity)."),

    # --- appendix: further related work (one-phrase descriptions) -------------------------
    ("gao2026engiworld", r"software", "EngiWorld evaluates agents on professional engineering software."),
    ("wan2025som1k", r"strength of materials", "SoM-1K is a strength-of-materials benchmark."),
    ("akbari2025circuitsense", r"synthetic", "CircuitSense uses synthetically generated circuit problems."),
    ("akbari2025circuitsense", r"schematic", "...posed from circuit schematics."),
    ("colle2025telemath", r"telecommunication", "TeleMath is a telecommunications-mathematics benchmark."),
    ("qin2026structureclaw", r"structural", "StructureClaw is an executable structural-engineering benchmark."),
    ("mohammadzadeh2025fembench", r"finite element", "FEM-Bench covers finite-element programming."),
    ("somasekharan2026cfdllmbench", r"computational fluid dynamics", "CFDLLMBench covers computational fluid dynamics."),
    ("silwal2026pecivilbench", r"PE Civil|Principles and Practice", "PE Civil Bench uses civil-engineering licensure exam questions."),
    ("sukpancharoen2026psebench", r"process systems engineering", "PSE-Bench covers process systems engineering..."),
    ("sukpancharoen2026psebench", r"judge", "...with LLM judges."),
    ("he2024olympiadbench", r"step-by-step", "OlympiadBench problems come with step-by-step expert solutions."),
    ("zhou2025scida", r"randomi[sz]", "SciDA randomises numerical parameters."),
    ("wang2023newton", r"template", "NEWTON generates questions from templates."),
    ("cheng2026vera", r"executable", "VeRA converts items into executable task families."),
    ("li2024gsmplus", r"perturbation", "GSM-Plus perturbs GSM8K problems."),
    ("tyen2023bigbenchmistake", r"logical mistake|first mistake|mistake finding", "BIG-Bench Mistake asks models to find mistakes in reasoning traces."),
    ("zeng2024mrben", r"meta-reasoning", "MR-Ben is a meta-reasoning benchmark."),
    ("he2025deltabench", r"long CoT|long chain", "DeltaBench detects errors in long chain-of-thought."),
    ("dong2026physprm", r"process reward", "PhysPRM is a process reward model..."),
    ("dong2026physprm", r"physics", "...for physics."),
    ("thakur2025judgingjudges", r"judge", "Judging the Judges evaluates LLM judges."),
    ("ye2025justiceprejudice", r"CALM", "CALM quantifies judge biases."),
    ("roytburg2026narcissists", r"self-preference", "Re-examines self-preference findings."),
    ("jung2025trustescalate", r"escalat", "Cascaded selective evaluation escalates uncertain items."),

    # --- comparison-table cells and wording added last --------------------------------------
    ("xie2025finchain", r"correlated with expert-assigned Reasoning Process Quality", "The 0.655 is a Spearman correlation with experts' ratings of reasoning-process quality."),
    ("fan2024hardmath", r"rubric|GPT-4o", "HARDMath grades with an LLM using rubrics."),
    ("yu2026hipho", r"judge", "HiPhO applies the marking schemes with an LLM judge."),
    ("he2024olympiadbench", r"final answer|automatic(ally)? (scor|evaluat)", "OlympiadBench scores final answers automatically."),
    ("heesch2025realworld", r"examination materials where correctness is easily verifiable", "Heesch et al. question evaluations adapted from examination materials where correctness is easily verifiable."),

    # --- appendix additions after the final check ------------------------------------------
    ("wang2026milestoneoracles", r"teacher model writes a fixed roadmap of intermediate sub-goals \(milestones\)", "A teacher model writes milestone roadmaps..."),
    ("wang2026milestoneoracles", r"deterministic symbolic verifier grades every answer", "...graded by a deterministic symbolic verifier."),
    ("zhao2025genprm", r"code verification", "GenPRM verifies each step with code."),
    ("jain2025agreeableness", r"True Negative Rate < 25%", "Judges identify few invalid outputs (TNR below 25%)..."),
    ("jain2025agreeableness", r"True Positive Rate > 96%", "...while accepting valid ones (TPR above 96%)."),
    ("yeadon2026physicsjudge", r"against human markers", "Frontier judges are compared with human markers in physics."),
    ("bavaresco2025llmsinsteadofhumans", r"should be carefully validated against human judgments", "Judges should be validated against human judgments before use."),
    ("yeadon2026physicsjudge", r"sharply task-dependent", "Their agreement with human markers depends on the task."),

    # --- added by the follow-up review of the 18 main-text papers (notes/followup_review.md) ------
    ("zhao2026prismphysics", r"fully rule-based", "PRISM-Physics' formula matching is fully rule-based."),
    ("zhao2026prismphysics", r"Ph\.D\. Qualifying Questions and Solutions", "Its problems come from a book of PhD qualifying-exam questions."),
    ("zhao2026prismphysics", r"randomly sampled 70 problems", "The human check covers 70 problems..."),
    ("zhao2026prismphysics", r"independently evaluated by two human experts", "...each scored by two experts."),
    ("zhao2026prismphysics", r"LLM-as-Judge is purely outcome-based", "The LLM-judge baseline is outcome-based."),
    ("akhtar2026benchmarksaturation", r"Hiding test data does not appear to prevent saturation", "Private test sets do not appear to prevent saturation (H1)."),
    ("akhtar2026benchmarksaturation", r"templated benchmarks \(N = 14\) do not differ significantly", "Templated benchmarks saturate no differently from non-templated ones (H6, p = 0.10)."),
    ("zhang2024gsm1k", r"partially memori[sz]ed", "GSM1k reads part of the overfitting as partial memorisation of GSM8k."),
    ("huang2025mathperturb", r"memorizes the problem-solving techniques", "MATH-Perturb: models memorise solution techniques and apply them where they no longer fit."),
    ("dlugosz2026gsmsymbolicreeval", r"only 8 exhibit statistically significant performance changes", "Only 8 of 20 re-evaluated models show significant changes on GSM-Symbolic."),
    ("lunardi2025paraphraserobustness", r"multiple-choice question answering setting", "Lunardi et al.'s benchmarks are multiple choice."),
    ("li2025atmosscibench", r"MCQEvaluator", "AtmosSci-Bench scores its generated multiple-choice questions by the option chosen."),
    ("li2025atmosscibench", r"OEQ dataset \(391 questions\)", "It has 391 open-ended questions without perturbation..."),
    ("li2025atmosscibench", r"cascade of evaluators", "...scored by a numeric, then symbolic, then LLM cascade."),
    ("li2025atmosscibench", r"92\.79", "Its LLM grader agreed with human graders on 92.79%..."),
    ("li2025atmosscibench", r"93\.02", "...and 93.02% of the open-ended answers it decided."),
    ("kevian2024controlbench", r"accuracy, reasoning, and explanatory", "ControlBench's expert panel examined accuracy, reasoning and explanations."),
    ("kevian2024controlbench", r"seven error types", "The experts sorted the failures into seven error types."),
    ("chen2026optengine", r"ten canonical Operations Research problems", "OPT-Engine spans ten canonical operations-research problems."),
    ("chen2026optengine", r"quantifiable and controllable complexity", "OPT-Engine's complexity is quantifiable and controllable..."),
    ("chen2026optengine", r"generates a vast repository of problem instances", "...and it generates problem instances with verifiable optimal solutions."),
    ("wang2026prime", r"college-level STEM problems", "PRIME is built from college-level STEM problems..."),
    ("wang2026prime", r"Mathematics, Physics, Chemistry, and Engineering", "...spanning mathematics, physics, chemistry and engineering."),
    ("tan2025judgebench", r"many strong models", "Many strong models perform just slightly better than random guessing."),
    ("krumdick2026nofreelabels", r"when not provided with a correct reference", "The condition is a correct reference."),
    ("huang2026verifierrobustness", r"supplementary judgment only when the rule-based verifier flags", "The hybrid asks the model only about responses the rule-based verifier rejects."),
    ("ansari2026physicsregrading", r"rule-based evaluators, which can fail to recognize a correct answer", "Rule-based graders can fail to recognise a correct answer in an equivalent form."),
    ("ansari2026physicsregrading", r"Grader errors dominate the audited cases on PHYBench and PRISM-Physics", "Grader errors dominate on the benchmarks with rule-based evaluators."),

    # --- claims used in the replacement sentences for the Introduction and section 4 (CHANGES.md) ---
    ("zhao2023survey", r"correct answer following an invalid reasoning path", "A correct answer can follow an invalid reasoning path."),
    ("wang2019superglue", r"88\.4", "SuperGLUE documents GLUE's saturation (best score 88.4)..."),
    ("wang2019superglue", r"87\.1", "...against a non-expert human estimate of 87.1."),
    ("kazemi2025bbeh", r"(over|above|exceed\w*) 90", "BBEH documents BBH's saturation above 90%."),
    ("hendrycks2021mmlu", r"world knowledge and problem solving ability", "MMLU tests world knowledge and problem-solving ability."),
    ("chen2021humaneval", r"BLEU", "HumanEval's authors find BLEU does not track functional correctness."),
    ("zhang2020bertscore", r"factual error", "BERTScore's authors note it has difficulty detecting factual errors."),
    ("chen2023frugalgpt", r"cascade", "FrugalGPT is an LLM cascade."),
]
