#!/usr/bin/env python
"""Dedupe the candidate catalogue and write the candidate review batches.

1. Same arXiv id under two keys: keep the key that has a text file (or the first in catalogue
   order), drop the other entry from its catalogue file and delete its PDF and text.
2. Same key in two files: fetch_papers.py already keeps the first; nothing to do.
3. Write notes/review_batches_candidate.md: candidates grouped by the Related Work paragraph their
   search topic maps to, sorted must > should > optional, chunked into batches; the number of
   independent reviewers per batch follows its priority (must 3, should 2 for engineering and 1
   otherwise, optional 1), as review_protocol.md records.

Usage: python make_candidate_batches.py [--dry-run]
"""
import argparse
import collections
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
TOPIC_PARAGRAPH = {
    "engineering_web": ("ENG", "engineering benchmarks"),
    "engineering_arxiv": ("ENG", "engineering benchmarks"),
    "physics_science": ("PHYS", "physical sciences and general science suites"),
    "symbolic_contamination": ("SYM", "symbolic generation, contamination and robustness"),
    "process_supervision": ("PROC", "process supervision and step-level verification"),
    "llm_judge": ("JUDGE", "LLM-judge validity and meta-evaluation"),
}
BATCH_SIZE = 12


def priority(e):
    n = e.get("notes", "")
    return "must" if "must-cite" in n else ("should" if "should-cite" in n else "optional")


def reviewers_for(group, prio):
    if prio == "must":
        return 3
    if prio == "should":
        return 2 if group == "ENG" else 1
    return 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    files = sorted(glob.glob(os.path.join(HERE, "candidates", "*.json")))
    data = {f: json.load(open(f, encoding="utf-8")) for f in files}
    text_dir = os.path.join(HERE, "text")
    have_text = {os.path.basename(p)[:-4] for p in glob.glob(os.path.join(text_dir, "*.txt"))}

    # 1. arXiv-id duplicates under different keys
    seen_key, by_id = set(), collections.defaultdict(list)
    for f in files:
        for e in data[f]:
            if e["key"] in seen_key:
                continue
            seen_key.add(e["key"])
            if e.get("arxiv"):
                by_id[e["arxiv"]].append((f, e["key"]))
    dropped = []
    for aid, lst in by_id.items():
        if len(lst) < 2:
            continue
        keep = next((k for k in lst if k[1] in have_text), lst[0])
        for f, key in lst:
            if (f, key) == keep:
                continue
            dropped.append((key, aid, keep[1]))
            if not args.dry_run:
                data[f] = [e for e in data[f] if e["key"] != key]
                for ext, d in ((".pdf", "papers"), (".txt", "text")):
                    p = os.path.join(HERE, d, key + ext)
                    if os.path.exists(p):
                        os.remove(p)
    if not args.dry_run:
        for f in files:
            with open(f, "w", encoding="utf-8") as fh:
                json.dump(data[f], fh, indent=1, ensure_ascii=False)
                fh.write("\n")
    for key, aid, kept in dropped:
        print(f"dropped {key} (arXiv {aid}); kept {kept}")

    # 2. the catalogue after dedupe, first occurrence of each key
    cat, order = {}, []
    for f in files:
        for e in data[f]:
            if e["key"] not in cat:
                cat[e["key"]] = e
                order.append(e["key"])
    groups = collections.defaultdict(list)
    for k in order:
        e = cat[k]
        g = TOPIC_PARAGRAPH.get(e.get("found_by"), ("OTHER", "unmapped topic"))[0]
        groups[g].append(e)

    # 3. batches
    lines = ["# Review batches: the candidate set", "",
             "Generated by `make_candidate_batches.py` from `candidates/*.json` after dedupe. Each batch is",
             "reviewed by the number of independent reviewers its priority sets (must 3; should 2 in ENG, 1",
             "elsewhere; optional 1). Reviewers follow `review_prompt_template.md` with SET = candidate.", ""]
    summary = []
    rank = {"must": 0, "should": 1, "optional": 2}
    for g in ("ENG", "PHYS", "SYM", "PROC", "JUDGE", "OTHER"):
        if g not in groups:
            continue
        para = next(v[1] for v in TOPIC_PARAGRAPH.values() if v[0] == g) if g != "OTHER" else "unmapped"
        for prio in ("must", "should", "optional"):
            items = [e for e in groups[g] if priority(e) == prio]
            if not items:
                continue
            n_rev = reviewers_for(g, prio)
            n_chunks = -(-len(items) // BATCH_SIZE)  # ceil: even split, no batch above BATCH_SIZE
            chunks = [items[i::n_chunks] for i in range(n_chunks)]
            for ci, chunk in enumerate(chunks, 1):
                name = f"{g}-{prio}-{ci}"
                summary.append((name, len(chunk), n_rev))
                lines.append(f"## Batch {name}: {para}, {prio}-cite candidates ({len(chunk)} papers, {n_rev} reviewer{'s' if n_rev > 1 else ''})")
                lines.append("")
                lines.append("| key | title | year | venue | found by | search note |")
                lines.append("|---|---|---|---|---|---|")
                for e in chunk:
                    note = e.get("notes", "").replace("|", "/")
                    lines.append(f"| {e['key']} | {e['title'].replace('|', '/')} | {e.get('year')} | {str(e.get('venue')).replace('|', '/')} | {e.get('found_by')} | {note} |")
                lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| batch | papers | reviewers | agent runs |")
    lines.append("|---|---:|---:|---:|")
    total_runs = 0
    for name, n, r in summary:
        total_runs += r
        lines.append(f"| {name} | {n} | {r} | {r} |")
    lines.append(f"| **total** | {sum(n for _, n, _ in summary)} | | {total_runs} |")
    out = os.path.join(HERE, "notes", "review_batches_candidate.md")
    if not args.dry_run:
        with open(out, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
    print(f"{len(cat)} candidates in {len(summary)} batches, {total_runs} reviewer runs; written to {out}")
    missing = [k for k in cat if k not in have_text and k not in {d[0] for d in dropped}]
    print("candidates without a text file:", missing)


if __name__ == "__main__":
    main()
