#!/usr/bin/env python
"""Tally the panel reviews: verdicts and recommendations per paper, and review coverage.

Writes notes/review_tally.md and prints it. Reads papers.json, candidates/*.json and
reviews/{cited,candidate}/<key>.<reviewer>.json.
"""
import collections
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def load(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def short_rec(r):
    r = (r or "").lower()
    for k, v in (("replace", "replace"), ("drop", "drop"), ("add (must)", "add-must"),
                 ("add (should)", "add-should"), ("add (optional)", "add-opt"),
                 ("keep as is", "keep"), ("keep, reword", "reword"), ("keep", "keep")):
        if k in r:
            return v
    return r[:12] or "?"


def main():
    cited = load(os.path.join(HERE, "papers.json"))
    cands, seen = [], set()
    for f in sorted(glob.glob(os.path.join(HERE, "candidates", "*.json"))):
        for e in load(f):
            if e["key"] not in seen:
                seen.add(e["key"])
                cands.append(e)
    reviews = collections.defaultdict(dict)
    for s in ("cited", "candidate"):
        for f in glob.glob(os.path.join(HERE, "reviews", s, "*.json")):
            key, rev = os.path.basename(f)[:-5].rsplit(".", 1)
            reviews[(s, key)][rev] = load(f)
    out = ["# Review tally", "", "Generated by `tally_reviews.py`.", "",
           "## Cited set: the May paper's citations", "",
           "| key | cited as | verdicts r1 / r2 / r3 | recommendations r1 / r2 / r3 | verdicts agree |",
           "|---|---|---|---|---|"]
    agree = 0
    for e in cited:
        rv = reviews.get(("cited", e["key"]), {})
        v = [rv.get(r, {}).get("engtrace_use", {}).get("verdict", "-") for r in ("r1", "r2", "r3")]
        rec = [short_rec(rv.get(r, {}).get("recommendation")) for r in ("r1", "r2", "r3")]
        same = len(set(x.split()[0] for x in v if x != "-")) == 1
        agree += same
        out.append(f"| {e['key']} | {e.get('cited_as')} | {' / '.join(v)} | {' / '.join(rec)} | {'yes' if same else 'no'} |")
    out += ["", f"Verdicts agree across the three reviewers for {agree} of {len(cited)} papers.", "",
            "## Candidate set: panel coverage", "",
            "| key | priority (search) | found by | reviews | recommendations |", "|---|---|---|---:|---|"]
    n_rev = collections.Counter()
    for e in cands:
        rv = reviews.get(("candidate", e["key"]), {})
        n_rev[len(rv)] += 1
        pri = "must" if "must-cite" in e.get("notes", "") else ("should" if "should-cite" in e.get("notes", "") else "optional")
        recs = ", ".join(f"{r}:{short_rec(d.get('recommendation'))}" for r, d in sorted(rv.items()))
        out.append(f"| {e['key']} | {pri} | {e.get('found_by')} | {len(rv)} | {recs} |")
    out += ["", "Candidates by number of panel reviews: " +
            ", ".join(f"{k} reviews: {v}" for k, v in sorted(n_rev.items())) + "."]
    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "notes", "review_tally.md"), "w", encoding="utf-8") as fh:
        fh.write(text)
    print(text)


if __name__ == "__main__":
    main()
