#!/usr/bin/env python
"""Check each factual claim the revised Related Work makes about a paper against the paper's text.

facts.py holds FACTS, a list of (key, regex, claim). For each one this script searches the paper's
extracted text (text/<key>.txt), page by page, after joining hyphenated line breaks and collapsing
whitespace, case-insensitively. It reports the page and a snippet around the first match, or
NOT FOUND. Output: notes/fact_check.md (and stdout). A claim whose pattern is not found must be
re-checked by hand or removed from the text.

Usage: python verify_facts.py [--only KEY ...] [--quiet]
"""
import argparse
import sys
import importlib.util
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))


def pages(key):
    path = os.path.join(HERE, "text", key + ".txt")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8", errors="replace") as fh:
        raw = fh.read().replace("\x00", "")
    parts = re.split(r"===== PAGE (\d+) =====", raw)
    out = []
    if len(parts) == 1:
        out.append((1, raw))
    else:
        for i in range(1, len(parts) - 1, 2):
            out.append((int(parts[i]), parts[i + 1]))
    norm = []
    ligatures = {"ﬀ": "ff", "ﬁ": "fi", "ﬂ": "fl", "ﬃ": "ffi", "ﬄ": "ffl"}
    for p, t in out:
        for a, b in ligatures.items():
            t = t.replace(a, b)
        t = re.sub(r"-\s*\n\s*", "", t)          # join hyphenated line breaks
        t = re.sub(r"\s+", " ", t)
        norm.append((p, t))
    return norm


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", nargs="*")
    ap.add_argument("--quiet", action="store_true", help="print only failures and the summary")
    args = ap.parse_args()
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    spec = importlib.util.spec_from_file_location("facts", os.path.join(HERE, "facts.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    facts = mod.FACTS
    if args.only:
        facts = [f for f in facts if f[0] in set(args.only)]
    lines = ["# Fact check of the revised Related Work", "",
             "Generated by `verify_facts.py` from `facts.py`. Each row is a claim the revised text makes about a",
             "paper, the pattern searched for in the paper's extracted text, and where it was found.", "",
             "| # | key | claim | page | evidence |", "|---:|---|---|---:|---|"]
    found = 0
    cache = {}
    for i, (key, pattern, claim) in enumerate(facts, 1):
        if key not in cache:
            cache[key] = pages(key)
        pg = cache[key]
        if pg is None:
            row = (i, key, claim, "-", "NO TEXT FILE")
        else:
            hit = None
            for p, t in pg:
                m = re.search(pattern, t, flags=re.I)
                if m:
                    a, b = max(0, m.start() - 70), min(len(t), m.end() + 70)
                    hit = (p, t[a:b].replace("|", "/"))
                    break
            if hit:
                found += 1
                row = (i, key, claim, hit[0], "..." + hit[1] + "...")
            else:
                row = (i, key, claim, "-", "NOT FOUND")
        lines.append("| {} | {} | {} | {} | {} |".format(*row))
        if not args.quiet or row[3] == "-":
            print(f"[{row[0]}] {row[1]} p{row[3]}: {row[2]}\n      {row[4][:240]}")
    summary = f"{found} of {len(facts)} claims found in the paper text."
    lines += ["", summary]
    if not args.only:
        with open(os.path.join(HERE, "notes", "fact_check.md"), "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
    print(summary)


if __name__ == "__main__":
    main()
