"""D-160: the two parser gaps older than both digit-rule fixes, measured as switches on the rule as it
stands; the thousands spelling's share of the third fix's removals; and the session's reading of each
gap's new flags.

    python -m full_run_28092026.gap_check      # FREE: writes GAP_CHECK.md (counts only)

THE GAPS. Both review agents found two gaps older than either fix far larger than the fixes' own
regressions: a LaTeX control space before a unit (`229.0\\ \\text{rad/s}`) left its segment unread, and a
line whose only relation is `≈` was never read. The owner closed the first and left the second (D-160).
Each is measured with digit_fix's comparisons on `arith.py` as it stands: the control space as the rule
without it against the rule, `≈`-only lines as the rule against the rule with them.

THE READING. Twenty steps each gap newly flagged were read in the session that closed one, drawn with seed
11 from the steps it flagged against the candidate rule of that moment. The verdicts are local, beside
the review agents' (scores/flag_review/agent_review/gap_verdicts_space.json, gap_verdicts_approx.json);
they are counted here, with how many of the twenty the gap, as measured here, still flags.
"""
from __future__ import annotations

import collections
import json

from full_run_28092026 import digit_fix as dfx

HERE = dfx.HERE
# Each switch is a one-line change to arith.py as it stands: (the text now, the text with the switch
# thrown). `closed` says which side is the rule as adopted.
GAPS = {
    'space': {'name': 'the LaTeX control space', 'closed': True,
              'now': "r'\\\\(?:left|right|displaystyle|,|;|!| |quad|qquad)'",
              'switched': "r'\\\\(?:left|right|displaystyle|,|;|!|quad|qquad)'"},
    'approx': {'name': 'lines whose only relation is `≈`', 'closed': False,
               'now': "        if '=' not in raw:\n",
               'switched': "        if '=' not in raw and '≈' not in raw and '\\\\approx' not in raw:\n"},
}
THIN = ',\\!'


def sources(gap: dict) -> tuple[str, str]:
    """(the rule without the gap closed, the rule with it closed)."""
    now = (dfx.EVAL / 'arith.py').read_text(encoding='utf-8')
    if now.count(gap['now']) != 1:
        raise SystemExit(f"arith.py no longer holds the switch for {gap['name']}: {gap['now']!r}")
    other = now.replace(gap['now'], gap['switched'])
    return (other, now) if gap['closed'] else (now, other)


def measure(key: str) -> dict:
    without, with_ = sources(GAPS[key])
    pre, post = dfx.load(without, f'gap_{key}_without'), dfx.load(with_, f'gap_{key}_with')
    per, changes = dfx.full_run(without, with_)
    tot = collections.Counter()
    for m in per.values():
        tot.update(m)
    verdicts = json.loads((dfx.REVIEW / f'gap_verdicts_{key}.json').read_text(encoding='utf-8'))
    added = {(c['model'], c['item_id'], c['step']) for c in changes if not c['before']}
    return {'gold': dfx.gold(without, with_), 'pilot': dfx.pilot(pre, post),
            'rounds': {r: dfx.reading(pre, post, r) for r in ('round1', 'round2')}, 'full': tot,
            'read': collections.Counter(v['verdict'] for v in verdicts),
            'still': sum((v['model'], v['item_id'], v['step']) in added for v in verdicts)}


def thousands() -> tuple[int, int]:
    """Of the third fix's steps losing a flag (scores/digit_fix_3_changes.jsonl), how many write `,\\!`."""
    changes = [json.loads(x) for x in (dfx.score.SCORES / 'digit_fix_3_changes.jsonl')
               .read_text(encoding='utf-8').splitlines()]
    texts, n, removed = {}, 0, 0
    for c in changes:
        if not c['before']:
            continue
        if c['model'] not in texts:
            rows = {r['item_id']: r for r in map(json.loads, (dfx.score.SCORES / 'main' / f"{c['model']}.jsonl")
                                                  .read_text(encoding='utf-8').splitlines())}
            texts[c['model']] = dfx.score.texts_matching('main', c['model'], rows.values())
        removed += 1
        n += THIN in dfx.e2_prm.steps_of(texts[c['model']][c['item_id']])[c['step']]
    return n, removed


def main() -> int:
    m = {k: measure(k) for k in GAPS}
    n, removed = thousands()

    def row(label, f):
        return f"| {label} | {f(m['space'])} | {f(m['approx'])} |"

    def rd(x, r, v):
        c = x['rounds'][r]
        return f"{c[('reproduced before', v)]} / {c[(v, 'the same claim')]}"
    L = ["# The digit rule's two older parser gaps, measured on the rule as it stands (D-160)", '',
         'Generated by `gap_check.py`; the switches and the reading are defined in its docstring. Each cell is '
         'the rule without the gap closed / with it closed.', '',
         f"| | {GAPS['space']['name']} (closed) | {GAPS['approx']['name']} (left) |", '|---|---:|---:|',
         row('gold: claims flagged', lambda x: f"{x['gold']['flagged before']} / {x['gold']['flagged after']}"),
         row("the pilot: steps whose flag moves toward / away from the experts",
             lambda x: f"{x['pilot']['moved']['toward']} / {x['pilot']['moved']['away']}"),
         row("round 1: slips flagged as the same claim", lambda x: rd(x, 'round1', 'slip')),
         row("round 1: the expert's misreadings still flagged", lambda x: rd(x, 'round1', 'checker')),
         row("round 2: slips flagged as the same claim", lambda x: rd(x, 'round2', 'slip')),
         row("round 2: the expert's misreadings still flagged", lambda x: rd(x, 'round2', 'checker')),
         row('the full run: claims read', lambda x: f"{x['full']['claims before']} / {x['full']['claims after']}"),
         row('the full run: claims flagged', lambda x: f"{x['full']['flagged before']} / {x['full']['flagged after']}"),
         row('the full run: steps whose flag appears / disappears',
             lambda x: f"{x['full']['steps flag added']} / {x['full']['steps flag removed']}"),
         row('the reading of 20 new flags: slip / checker / unsure',
             lambda x: f"{x['read']['slip']} / {x['read']['checker']} / {x['read']['unsure']}"),
         row('of those 20, flagged by the gap as measured here', lambda x: str(x['still'])), '',
         'Pilot steps moving away from the experts: '
         + '; '.join(f"{GAPS[k]['name']}: " + (', '.join(f'{c} step {j}' for c, j in sorted(m[k]['pilot']['away']))
                                                 or 'none') for k in GAPS) + '.', '',
         f"The third fix's thousands spelling: {n} of the {removed} steps losing a flag in `DIGIT_FIX_3.md` write "
         'thousands as `,\\!`, which the rule before it split into claims such as `000 = 776`.']
    (HERE / 'GAP_CHECK.md').write_text('\n'.join(L) + '\n', encoding='utf-8', newline='\n')
    print('\n'.join(L))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
