"""D-139: which verdict word is the answer, measured before any change.

    python -m full_run_28092026.word_audit     # FREE: writes WORD_AUDIT.md beside this file

THE WEAKNESS. A classification answer's word is checked by its LAST mention among all verdict
words (`answer._word_hit`), so that an answer restating the criteria is not credited for every
regime it names. But every verdict word competes with every other, and a negated one counts:
"critically damped; omega_d = 0 (no oscillation occurs)" ends on `no`, and "critically damped ...
since the system is not underdamped" on `underdamped`.

TWO CANDIDATE RULES, each measured alone and together, against the D-138 check:
  F   only the target's own family competes: damping (overdamped, underdamped, critically,
      undamped), flow regime (laminar, turbulent, transitional), and so on; a word in no family
      competes with all, as before
  N   a mention negated just before it ("not", "non-", "n't", "never", "neither", "nor") is skipped
Measured on the gold, on the pilot's 300 traces against the experts and on every full-run trace.
The variants are defined here in full and applied in memory.
"""
from __future__ import annotations

import collections
import concurrent.futures as cf
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
EVAL = REPO / 'evaluator_pilot_17092026' / 'evaluators'
for p in (str(REPO), str(EVAL), str(REPO / 'evaluation')):
    if p not in sys.path:
        sys.path.insert(0, p)

import answer  # noqa: E402

from full_run_28092026 import score  # noqa: E402

FAMILIES = [('overdamped', 'underdamped', 'critically', 'undamped'), ('laminar', 'turbulent', 'transitional'),
            ('safe', 'unsafe'), ('yes', 'no'), ('feasible', 'infeasible'), ('stable', 'unstable'),
            ('acceptable', 'adequate', 'inadequate'), ('subsonic', 'supersonic'), ('saturated', 'superheated'),
            ('subcritical', 'supercritical'), ('operational', 'failed')]
NEGATED = re.compile(r"(?:\bnot|\bnon-?|n't|\bnever|\bneither|\bnor)\s*(?:\w+\s+)?$")


def word_hit(low, w, family, negation):
    if w in answer.LINEAR:
        vocab = answer.LINEAR
    elif family:
        vocab = next((f for f in FAMILIES if w in f), tuple(sorted(answer.VERDICT_WORDS)))
    else:
        vocab = sorted(answer.VERDICT_WORDS)
    last = None
    for m in re.finditer(r'\b(%s)\b' % '|'.join(vocab), low):
        if negation and NEGATED.search(low[max(0, m.start() - 24):m.start()]):
            continue
        last = m.group(1)
    return last == w


VARIANTS = {'D-138': (False, False), 'F': (True, False), 'N': (False, True), 'F+N': (True, True)}


def use(name):
    fam, neg = VARIANTS[name]
    answer._word_hit = lambda low, w: word_hit(low, w, fam, neg)


def _gold(name):
    use(name)
    items = score.pool_items()
    ms = score.milestone_sets(items)
    return name, sum(answer.verdict(it['solution'], it, None, tuple(m['value'] for m in ms[i]))[0] == 'correct'
                     for i, it in items.items())


def _pilot(name):
    use(name)
    from full_run_28092026 import validate_scorer as V
    truth, keyfile, items, texts = V.pilot_inputs()
    lab, exp = {}, {}
    for code, t in truth.items():
        key = keyfile[code]
        if key[1] in items and key in texts:
            lab[code] = answer.verdict(texts[key], items[key[1]], None, tuple(m['value'] for m in t['milestones']))[0]
            exp[code] = t['final_answer']
    np_codes = [c for c in lab if exp[c] != 'partial']
    return name, {'non_partial': sum((lab[c] == 'correct') == (exp[c] == 'correct') for c in np_codes) / len(np_codes),
                  'three_way': sum(lab[c] == exp[c] for c in lab) / len(lab), 'labels': lab, 'experts': exp}


def _model(key):
    items = score.pool_items()
    ms = score.milestone_sets(items)
    out = {name: {} for name in VARIANTS}
    for r in score.trace_rows('main', key):
        it = items[r['item_id']]
        if it['answer_type'] != 'classification':
            continue
        for name in VARIANTS:
            use(name)
            text = r.get('text') or ''
            out[name][r['item_id']] = (answer.verdict(text, it, None, tuple(m['value'] for m in ms[r['item_id']]))[0]
                                       if r.get('status') == 'answered' and score.readable(text) else 'unusable')
    return key, out


def main() -> int:
    from full_run_28092026.run_traces import config as roster
    keys = [m['key'] for m in roster()['models'] if (score.TRACES / f"{m['key']}.jsonl").exists()]
    with cf.ProcessPoolExecutor(max_workers=8) as pool:
        gold = dict(pool.map(_gold, VARIANTS))
        pilot = dict(pool.map(_pilot, VARIANTS))
        runs = dict(pool.map(_model, keys))
    base, exp = pilot['D-138']['labels'], pilot['D-138']['experts']
    items = score.pool_items()
    L = ['# Which verdict word is the answer (D-139)', '',
         'Generated by `word_audit.py`; the weakness and the candidate rules are defined in its docstring. '
         'Counts only.', '', '## The gold and the pilot', '',
         '| check | gold scored correct | pilot non-partial agreement | pilot three-way agreement | '
         'pilot verdicts changed | to the experts\' verdict | away from it |', '|---|---:|---:|---:|---:|---:|---:|']
    for name in VARIANTS:
        lab = pilot[name]['labels']
        moved = [c for c in lab if lab[c] != base[c]]
        L.append(f"| {name} | {gold[name]} of 2250 | {pilot[name]['non_partial']:.3f} | {pilot[name]['three_way']:.3f} | "
                 f"{len(moved)} | {sum(lab[c] == exp[c] for c in moved)} | {sum(base[c] == exp[c] for c in moved)} |")
    L += ['', f'## The full run: the {len(next(iter(runs.values()))["D-138"])} classification items per model', '',
          '| model | F: changed | N: changed | F+N: changed | F+N transitions |', '|---|---:|---:|---:|---|']
    total = collections.Counter()
    for k, v in runs.items():
        ch = {n: [i for i in v['D-138'] if v[n][i] != v['D-138'][i]] for n in ('F', 'N', 'F+N')}
        tr = collections.Counter(f"{v['D-138'][i]} -> {v['F+N'][i]}" for i in ch['F+N'])
        for i in ch['F+N']:
            total[items[i]['template_id'].removeprefix('template_')] += 1
        L.append(f"| `{k}` | {len(ch['F'])} | {len(ch['N'])} | {len(ch['F+N'])} | "
                 + '; '.join(f'{t} {n}' for t, n in tr.most_common()) + ' |')
    L += ['', 'F+N changes by template: ' + ', '.join(f'`{t}` {n}' for t, n in total.most_common()) + '.']
    (HERE / 'WORD_AUDIT.md').write_text('\n'.join(L) + '\n', encoding='utf-8', newline='\n')
    print('\n'.join(L))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
